name: Triage and Dispatch

on: 
  push:
    branches:
      - '**' 
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-pre'
  pull_request:
    branches:
      - master  
      
jobs:
  dispatch_build:
    runs-on: ubuntu-latest
    outputs:
      run_id: ${{ steps.dispatch_build.outputs.run_id }}
      run_url: ${{ steps.dispatch_build.outputs.run_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set create_release variable
        id: set_create_release
        run: |
          if [[ "${GITHUB_REF}" =~ [0-9]+\.[0-9]+\.[0-9]+-pre ]]; then
            echo "::set-output name=create_release::debug"
          elif [[ "${GITHUB_REF}" =~ [0-9]+\.[0-9]+\.[0-9]+ ]]; then
            echo "::set-output name=create_release::release"
          fi

      - name: Dispatch build workflow and get the run ID
        id: dispatch_build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build.yml
          token: ${{ secrets.AUTH_GITHUB_API }}
          ref: ${{ github.ref }}
        env:
          CREATE_RELEASE: ${{ steps.set_create_release.outputs.create_release }}

      - name: Set outputs
        run: |
          echo "::set-output name=run_id::${{ steps.dispatch_build.outputs.run_id }}"
          echo "::set-output name=run_url::${{ steps.dispatch_build.outputs.run_url }}"

  wait_for_build:
    runs-on: ubuntu-latest
    needs: dispatch_build
    steps:
      - name: Wait for build to complete
        id: wait_for_build
        run: |
          run_id=${{ needs.dispatch_build.outputs.run_id }}
          token=${{ secrets.AUTH_GITHUB_API }}
          status="in_progress"
          while [[ "$status" == "in_progress" || "$status" == "queued" ]]; do
            echo "Waiting for build to complete..."
            sleep 10
            status=$(curl -s -H "Authorization: token $token" \
              https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id | jq -r .status)
          done
          conclusion=$(curl -s -H "Authorization: token $token" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id | jq -r .conclusion)
          echo "Build concluded with status: $conclusion"
          echo "::set-output name=conclusion::$conclusion"

      - name: Create a comment with the build result
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.AUTH_GITHUB_API }}
          repository: ${{ github.repository }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Build workflow has been triggered. [View build](${{ needs.dispatch_build.outputs.run_url }})
            Build concluded with status: ${{ steps.wait_for_build.outputs.conclusion }}

  wait_for_release:
    runs-on: ubuntu-latest
    needs: wait_for_build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Wait for release to complete
        id: wait_for_release
        run: |
          run_id=${{ needs.dispatch_build.outputs.run_id }}
          token=${{ secrets.AUTH_GITHUB_API }}
          status="in_progress"
          while [[ "$status" == "in_progress" || "$status" == "queued" ]]; do
            echo "Waiting for release to complete..."
            sleep 10
            status=$(curl -s -H "Authorization: token $token" \
              https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id | jq -r .status)
          done
          conclusion=$(curl -s -H "Authorization: token $token" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id | jq -r .conclusion)
          echo "Release concluded with status: $conclusion"
          echo "::set-output name=conclusion::$conclusion"

      - name: Extract tag from ref
        id: extract_tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "::set-output name=tag::$TAG_NAME"

      - name: Dispatch release workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: release.yml
          token: ${{ secrets.AUTH_GITHUB_API }}
          ref: ${{ github.ref }}
        env:
          CREATE_RELEASE: ${{ steps.set_create_release.outputs.create_release }}